### ISSUE TITLE
User experience improvement

### ISSUE THREAD

**Issue by jtoownus** [MLH/pong-game-horizen#2]
Hey Halisson,

I was wondering if we could still adopt an improvement with regards to UX.
The [TUTORIAL.md](https://github.com/MLH/pong-game-horizen/blob/master/TUTORIAL.md) states the following two steps:

* Provide your wallet address and click on "Check Payment". (This step usually takes just a few minutes, but in some instances, it took me hours.)
* The game will automatically start when the transaction gets 1 confirmation. (You should be able to check the number of confirmations by finding the transaction in your Wallet and clicking on "View on Blockchain")

When a new address is generated per game and per user, an incoming TX should be proof-enough that the user made the payment. I don't understand why the user would need to provide their wallet address.
For this specific use case, we could also accept zero-confirmation payments.

@megaluck What do you think?

I hope this suggestion can still be implemented given the curriculum development started.

**Comment by jtoownus** [comment]
Any update?

**Comment by chemiskitty** [comment]
@halissonvit Hey Bruno, do you think you could incorporate this feedback?

**Comment by jtoownus** [comment]
Guys, this has been way too long. Please provide feedback!

**Comment by jtoownus** [comment]
Guys?!

**Comment by chemiskitty** [comment]
Hi Jonas,

Not sure if you saw my email from a few days ago, we have someone else
working on it now. I'll check in on the status today and follow up on our
other email thread.

Thanks,
Kat O'Leary

Localhost Product Manager
(they/them)
